@RootUrl = http://localhost:5000

GET {{RootUrl}}/weatherforecast/
Accept: application/json

###
POST {{RootUrl}}/api/Auth/register
Accept: application/json
Content-Type: application/json
{
    "username": "testuser",
    "email": "sipho@gmail.com",
    "password": "testpassword"
}
